### PR TITLE
Do NOT merge it, but check them out tho

### PR DESCRIPTION
**Pull request by dendeaisd**
We need to double triple check that this merge would not fuck the commit history, my branch had still the old commit history from before my fuck up, so i had to replace all of the commits on my local branch and force push to github, to make the histories compatible

### CODE REVIEW

**Comment by letsgogeeky** [comment]
Wow that's great!! and super fancy xDD!!

About the history. yes, unfortunately, this cannot be merged. it would be best if you started a new branch from main and copy the work done here to the new branch. this one will bamboozle the repository xD!

**Comment by dendeaisd** [comment]
Not even if we merge and rebase? @letsgogeeky

**Comment by letsgogeeky** [comment]
> Not even if we merge and rebase? @letsgogeeky

We can try to first rebase your branch on main (locally) and then if the files marked as deleted is not in the changes anymore we can merge it.

**Comment by dendeaisd** [comment]
okyy

**Pull request merged**
